name:                ff-manager
version:             0.1.0.0
github:              "fetsh-edu/ff-manager"
license:             BSD3
author:              "fetsh"
maintainer:          "me@fetsh.me"
copyright:           "2021 fetsh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fetsh-edu/ff-manager#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-client
- http-client-tls
- http-conduit
- aeson
- time
- filepath
- directory

library:
  source-dirs: src

executables:
  ff-manager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ff-manager

tests:
  ff-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ff-manager
